version: '3.3'

services:
  app:
    build:
      context: ./DomainStatusChecker
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/New_York
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - ${PORT:-80}:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./DomainStatusChecker/wwwroot:/app/wwwroot:ro
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
  app_logs: